
export const AJAX_REQUEST = 'AJAX_REQUEST';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const AJAX_ERROR = 'AJAX_ERROR';

export const NAVIGATION = 'NAVIGATION';
export const NAVIGATION_REQUEST = 'NAVIGATION_REQUEST';
export const NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS';
export const NAVIGATION_ERROR = 'NAVIGATION_ERROR';

export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_REPOS_REQUEST = 'SEARCH_REPOS_REQUEST';
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
export const SEARCH_REPOS_ERROR = 'SEARCH_REPOS_ERROR';

export const REPO_DETAILS = 'REPO_DETAILS';