
export const AJAX_STATUS_REQUEST = 'AJAX_STATUS_REQUEST';
export const AJAX_STATUS_SUCCESS = 'AJAX_STATUS_SUCCESS';
export const AJAX_STATUS_ERROR = 'AJAX_STATUS_ERROR';

export const MOVIES_FILTER_TOP_RATED = 'MOVIES_FILTER_TOP_RATED';
export const MOVIES_FILTER_POPULAR = 'MOVIES_FILTER_POPULAR';
export const MOVIES_FILTER_PREMIER = 'MOVIES_FILTER_PREMIER';
export const MOVIES_FILTER_UPCOMING = 'MOVIES_FILTER_UPCOMING';
