
export const NAVIGATION_START = 'NAVIGATION_START';
export const NAVIGATION_END = 'NAVIGATION_END';

export const AJAX_STATUS_REQUEST = 'AJAX_STATUS_REQUEST';
export const AJAX_STATUS_SUCCESS = 'AJAX_STATUS_SUCCESS';
export const AJAX_STATUS_ERROR = 'AJAX_STATUS_ERROR';
